Relojeria/Relojeria/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	# urlpath / met views / nombre
    url(r'^admin/', admin.site.urls),
    url(r'^', view=include('apps.inicio.urls' , namespace="inicio")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Relojeria/apps/inicio/urls.py
from django.conf.urls import url
from .views import inicio, Listar_Articulos, Cargar_Venta, Ver_Proveedor, Lista_proveedores
# para importar la vista encargada de la auth ->
# from django.contrib.auth import views as authentication


urlpatterns = [
	# urlpath / met views / nombre
    url(r'^$', inicio, name='inicio'),
    url(r'^consulta/$', Listar_Articulos.as_view(), name='consulta'),
    url(r'^proveedor/$', Lista_proveedores.as_view(), name='proveedores'),
    url(r'^proveedor/(?P<pk>[\d]+)/', Ver_Proveedor.as_view(), name='proveedor'),
    url(r'^cargarventa/$', Cargar_Venta.as_view(), name='cargarventa'),
]

Relojeria/apps/inicio/models.py
from django.db import models

class TimeStampedModel(models.Model):
	creado = models.DateTimeField(auto_now_add=True,
								verbose_name=u'creado',
								help_text=u'Fecha de creacion')
	modificado = models.DateTimeField(auto_now=True,
								verbose_name=u'modificado',
								help_text=u'Fecha de modificacion')

	class Meta:
		abstract = True


class Proveedor(models.Model):

	nombre = models.CharField(max_length=50)

	def __str__(self):
		return self.nombre


class Articulo(models.Model):

	nombre = models.CharField(max_length=50)

	precio = models.DecimalField(max_digits=14, decimal_places=2)

	descripcion = models.CharField(max_length=100)

	proveedor = models.ForeignKey(Proveedor)

	def __str__(self):
		return self.nombre


class Venta(TimeStampedModel):

	total = models.DecimalField(max_digits=14, decimal_places=2)

	def __str__(self):
		return 'Venta-'+str(self.id)

class LineaVenta(models.Model):

	venta = models.ForeignKey(Venta)

	articulo = models.ForeignKey(Articulo)

	cantidad = models.IntegerField()

	def __str__(self):
		return str(self.venta)+'-LineaVenta-'+str(self.id)

Relojeria/apps/inicio/forms.py
from django import forms
from .models import LineaVenta, Venta

class FormVenta(forms.ModelForm):
	venta = forms.ModelChoiceField(queryset=Venta.objects.all())

	class Meta:
		model = LineaVenta
		exclude = ['venta']

Relojeria/apps/inicio/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy

from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView

from .models import Articulo, Proveedor, Venta, LineaVenta
from .forms import FormVenta

# Create your views here.
def inicio(request):
	
	return render (request, 'inicio/inicio.html')

class Lista_proveedores(ListView):
	model = Proveedor
	template_name= 'inicio/proveedores.html'

class Listar_Articulos(ListView):
	model = Articulo
	context_object_name = 'articulos'
	template_name= 'inicio/consulta.html'
	def get_context_data(self, **kwargs):
		context = super(Listar_Articulos, self).get_context_data(**kwargs)

		dic = {}
		lista = []
		prec = {}
		tot = []
		for i in context['object_list']:
			dic[i.nombre] = LineaVenta.objects.filter(articulo_id=i.id)
			lista.append(dic[i.nombre])
			cant = 0
			for d in dic[i.nombre]:
				print('||',d.cantidad,'||')
				cant = cant + d.cantidad
			print (dic[i.nombre],'|', cant*i.precio)
			prec[i.nombre] = cant*i.precio
			tot.append(prec[i.nombre])
			print ('::',tot,'::')
		context['ventas'] = lista
		context['total'] = prec
		return context

class Ver_Proveedor(DetailView):
	model = Proveedor
	context_object_name = 'proveedor'
	template_name= 'inicio/proveedor.html'

	def get_context_data(self, **kwargs):
		context = super(Ver_Proveedor, self).get_context_data(**kwargs)
		print (context['proveedor'].id)
		context['articulos'] = Articulo.objects.filter(proveedor=context['proveedor'].id)


		return context


class Cargar_Venta(FormView):
	template_name= 'inicio/cargarventa.html'
	form_class = FormVenta
	success_url = reverse_lazy('inicio:inicio')
	
	def form_valid(self, form):
		# This method is called when valid form data has been POSTed.
		# It should return an HttpResponse.
		venta = form.save(commit=False)
		print ('Exito', venta.articulo)
		return super(Cargar_Venta, self).form_valid(form)

Relojeria/templates/inicio/cargarventa.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message" />
</form>

Relojeria/templates/inicio/consulta.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Inicio | Relogería</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href={% static 'css/estilos.css' %}>
</head>

<body>
	<header>
		<div class="container">
			<h1>:: Relojería ::</h1>
		</div>
	</header>

	<div class="container">
		<div class="row">
			<div class="col-md-12 main">
				<h3>Articulos:</h3>
					<ul class="sinpuntos">
					{% for a in articulos %}
					<li>{{a.id}}</li>
					<li>{{a.nombre}}</li>
					<li>{{a.descripcion}}</li>
					<li>${{a.precio}}</li>
					<li>{{a.proveedor}}</li>
					<li>----------------------------</li>
					{% endfor %}
					</ul>
			</div>

			<div class="col-md-12 main">
				<h3>Informe de Ventas por Articulos:</h3><br>
					
					{% for a in articulos %}
					<h4>Articulo: {{a.nombre}} - {{a.proveedor}}</h4>
					<div class="table-responsive">
						<table class="table table-bordered table-hover">
							<tr class="danger">
								<th># Nro. Venta</th>
								<th>Fecha</th>
								<th>Cantidad</th>
								<th>Precio Unidad</th>
								<th>Total</th>
							</tr>
							{% for lista in ventas %}
							{% for l in lista %}
								{% if l.articulo == a %}
								<tr>
									<td>{{l.venta.id}}</td>
									<td>{{l.venta.creado}}</td>
									<td>{{l.cantidad}}</td>
									<td>${{l.articulo.precio}}</td>
									<td></td>
								</tr>
								{% endif %}
							{% endfor %}
							{% endfor %}


							{% for key,val in total.items %}
							
								{% if key == a.nombre %}
									<tr>
										<td></td>
										<td></td>
										<td></td>
										<td></td>
										<td class="success">${{val}}</td>
									</tr>
								{% endif %}
							
							{% endfor %}




						</table>
					</div>
					{% endfor %}




			</div>
		</div>
	</div>


	<!-- Latest compiled and minified JavaScript -->
	<script src="http://code.jquery.com/jquery-latest.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

Relojeria/templates/inicio/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Inicio | Relogería</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href={% static 'css/estilos.css' %}>
</head>

<body>
	<header>
		<div class="container">
			<h1>:: Relojería ::</h1>
		</div>
	</header>

	<div class="container">
		<div class="row">
			<div class="col-md-12 main">
				<h3>Consultar informe de Ventas:</h3>
				<a href="{% url 'inicio:consulta' %}"><button class="btn btn-primary">Consultar</button></a>

				<br><br>

				<h3>Lista de Proveedores:</h3>
				
			</div>
		</div>
	</div>


	<!-- Latest compiled and minified JavaScript -->
	<script src="http://code.jquery.com/jquery-latest.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

Relojeria/templates/inicio/proveedor.html
	<h1>{{proveedor.nombre}}</h1>
	
	<br>

	<h2>Articulos del Proveedor</h2>

	<ul>
	{% for a in articulos %}

		<li>
		{{a.id}} - {{a.nombre}} - {{a.cantidad}}
		</li>


	{% endfor %}
	</ul>

Relojeria/templates/inicio/proveedores.html
{% for p in object_list %}
<a href="{% url 'inicio:proveedor' p.id %}">{{p.nombre}}</a>
<br>
{% endfor %}