Intruzoz/Intruzoz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', view=include('apps.inicio.urls' , namespace="inicio")),
    url(r'^noticias/', view=include('apps.noticias.urls' , namespace="noticias")),
    # Editor WYSIWYG
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Intruzoz/apps/inicio/urls.py
from django.conf.urls import url, include
from .views import inicio, dos
from django.contrib.auth import views as authentication
""" aca importamos la vista encargada de la auth"""


urlpatterns = [
	# urlpath / met views / nombre
    url(r'^$', inicio, name='inicio'),
    url(r'^pag2/(?P<numero>[\d]{4})/$', dos, name='pag2'),
    url(r'^login/$', authentication.login,
    	{'template_name':'inicio/login.html'}, name='login'),
    url(r'^logout/$', authentication.logout_then_login, name='logout'),
]

Intruzoz/apps/login/urls.py
from django.conf.urls import url, include
from .views import login


urlpatterns = [
	# urlpath / met views / nombre
    url(r'^$', inicio, name='inicio'),
    #url(r'^pag2/(?P<numero>[\d]{4})/$', dos, name='pag2'),
]

Intruzoz/apps/noticias/urls.py
from django.conf.urls import url
from .views import (Listar_Noticias, Mostrar_Noticia, Editar_Noticia,
		 Eliminar_Noticia, Crear_Noticia, Contactar, Comentar_ajax)


urlpatterns = [
	# urlpath / met views / nombre
    url(r'^crear_noticia/', Crear_Noticia, name='crear_noticia'),
    url(r'^$', Listar_Noticias.as_view(), name='noticias'),
    url(r'^noticia/(?P<pk>[\d]+)/', Mostrar_Noticia.as_view(), name='noticia'),
    url(r'^Comentar_ajax/$', Comentar_ajax, name='comentar'),
    url(r'^editar_noticia/(?P<pk>[\d]+)/', Editar_Noticia.as_view(), name='editar_noticia'),
    url(r'^eliminar_noticia/(?P<pk>[\d]+)/', Eliminar_Noticia.as_view(), name='eliminar_noticia'),
    url(r'^contacto/', Contactar, name='contacto'),
]

Intruzoz/apps/inicio/models.py
from django.db import models

# Create your models here.

Intruzoz/apps/login/models.py
from django.db import models

# Create your models here.

Intruzoz/apps/inicio/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

def inicio(request):
	context = {}
	context['nombre'] = 'Facus'
	context['persona'] = ['nico', 'tortosa', '25']
	return render (request, 'inicio/inicio.html', context)

def dos(request, numero):
	return render (request, 'inicio/pag2.html')

"""
class Inicio2(TemplateView):
	template_name = 'inicio/inicio.html'
	def get_context_data(self, **kwargs):
		ctx = super(Inicio2,self).get_context_data(**kwargs)
		ctx['persona'] = ['nati', 'nati', 25]
		return ctx
"""

#def login(request):
#	return render (request, 'inicio/login.html')

Intruzoz/apps/login/views.py
from django.shortcuts import render

# Create your views here.

Intruzoz/templates/inicio/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Página de Práctica</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href={% static 'css/estilos.css' %}>
</head>
<body>
	<header>
		<div class="container">
			{% if user.is_authenticated %}
				<p class="pull-right">{{user.username}} <a href={% url 'inicio:logout' %}>(salir)</a></p>
			{% else %}
				<a href={% url 'inicio:login' %}><button class="btn btn-default pull-right">Ingresar</button></a>
			{% endif %}
			<h1>Página Web de Prácticas de {{nombre}}</h1>
			<h3>HTML y CSS</h3>
		</div>
	</header>
	
	<div class="container">
		<div class="main row">
			<article class="col-xs-12 col-sm-8 col-md-9">
				
				<h3>Articulo Principal</h3>
				<h4>Este artículo es el principal y contiene la información más importante</h4>

				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas laborum quasi dolorum, mollitia inventore sapiente consequatur odit veritatis eius voluptas aliquam numquam, porro non ea, vero placeat et! Nostrum, recusandae.
				</p>
				<figure>
					<img class="img-responsive" src="html5_css3.png" alt="html5 y css3">
				</figure>
				<wbr>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis possimus tenetur tempore voluptas aliquid labore minus, aliquam eum inventore adipisci nemo nulla libero, repellat ex distinctio dolorem vero dolor cupiditate, magnam aspernatur? Quod neque dignissimos ullam distinctio similique, at cumque eligendi deleniti maiores nisi doloribus hic labore, repellat atque consequuntur!
				</p>				
			</article>
		
			<aside class="col-xs-12 col-sm-4 col-md-3 col-lg-3">

				<h3>Sidebar con Aside</h3>
				<h4>Esto es un bloque destacado</h4>

				<p>
					Se utiliza para enfatizar algo del artículo principal, entre otras cosas
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
					cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
					proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</p>
				
			</aside>
		</div>

		<div class="row">
			<div class="color1 col-xs-12 col-sm-6 col-md-4">
				<h4>Sub-Categoría 1</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione ab qui laudantium dolor, sit doloremque aliquid earum nesciunt vero ullam commodi, blanditiis numquam natus libero repellat odit cum, ipsa nostrum!</p>
				<a href={% url 'inicio:pag2' 1978 %}><button class="btn btn-default btn-lg btn-block">Botón 1</button></a>
			</div>
			<div class="color2 col-xs-12 col-sm-6 col-md-4">
				<h4>Noticias</h4>
				<p>Enterate de las últimas noticias.</p>
				<a href={% url 'noticias:noticias' %}><button class="btn btn-default btn-lg btn-block">Ver Noticias</button></a>
			</div>

			<div class="color1 col-xs-12 col-sm-6 col-md-4">
				<h4>Contacto</h4>
				<p>Mantente en contacto con nosotros.</p>
				<p>Envíanos un correo electrónico mediante el formulario de contacto.</p>
				<a href={% url 'noticias:contacto' %}><button class="btn btn-default btn-lg btn-block">Contactate</button></a>
			</div>

		</div>
	</div>

	<footer>
		<div class="container">
			<h3>Pie de pagina - Footer</h3>
			<h4>Esto sirve para los links de fuentes, copyright y esa onda :P</h4>
		</div>
	</footer>
	</div>

	<!-- Latest compiled and minified JavaScript -->
	<script src="http://code.jquery.com/jquery-latest.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

Intruzoz/templates/inicio/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Ingresar | Página Web de Prácticas</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href={% static 'css/estilos.css' %}>
	<link rel="shortcut icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
	<link rel="icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
</head>
<body>
	<header>
		<div class="container">
			<h1>Página Web de Prácticas</h1>
		</div>
	</header>

	<div class="container">
	<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Ingreso</h1>
		<!-- Formulario de login -->
		<div class="login-container">
			{% if form.errors %}
				<div id="output" class="alert alert.danger animated fadeInUp">Error en las credenciales.</div>
			{% endif %}


			<div class="form-box">
			<form action="{% url 'inicio:login' %}" method="POST"> {% csrf_token %}
			  <div class="form-group">
			    <label for="InputUser1">Usuario</label>
			    <input type="text" name="username" class="form-control" id="InputUser1" placeholder="Usuario">
			  </div>
			  <div class="form-group">
			    <label for="InputPassword1">Contraseñas</label>
			    <input type="password" name="password" class="form-control" id="InputPassword1" placeholder="Password">
			  </div>
			  <button type="submit" class="btn btn-default">Ingresar!</button>
			  <input type="hidden" name="next" value="{{ next }}" />
			</form>
			</div>
		</div>
		<!-- Formulario de login -->
	</div>
	</div>
	</div>


</body>
</html>

Intruzoz/templates/inicio/pag2.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Soy una pagina</title>
</head>
<body>
	<h1>Hola!</h1>

	<h2>Apretaste el boton 1 ;)</h2>
</body>
</html>