Intruzoz/Intruzoz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', view=include('apps.inicio.urls' , namespace="inicio")),
    url(r'^noticias/', view=include('apps.noticias.urls' , namespace="noticias")),
    # Editor WYSIWYG
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Intruzoz/apps/noticias/urls.py
from django.conf.urls import url
from .views import (Listar_Noticias, Mostrar_Noticia, Editar_Noticia,
		 Eliminar_Noticia, Crear_Noticia, Contactar, Comentar_ajax)


urlpatterns = [
	# urlpath / met views / nombre
    url(r'^crear_noticia/', Crear_Noticia, name='crear_noticia'),
    url(r'^$', Listar_Noticias.as_view(), name='noticias'),
    url(r'^noticia/(?P<pk>[\d]+)/', Mostrar_Noticia.as_view(), name='noticia'),
    url(r'^Comentar_ajax/$', Comentar_ajax, name='comentar'),
    url(r'^editar_noticia/(?P<pk>[\d]+)/', Editar_Noticia.as_view(), name='editar_noticia'),
    url(r'^eliminar_noticia/(?P<pk>[\d]+)/', Eliminar_Noticia.as_view(), name='eliminar_noticia'),
    url(r'^contacto/', Contactar, name='contacto'),
]

Intruzoz/apps/noticias/models.py
from django.db import models
from django.template.defaultfilters import slugify
from apps.core.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class Noticia(TimeStampedModel):
	titulo = models.CharField(max_length=100,
							verbose_name='Title',
							help_text= 'Aca va el titulo',
				)
	resumen = models.CharField(max_length=200)
	cuerpo = RichTextUploadingField()
	TIPO_CHOICE = (
					('D', 'Deporte'),
					('P', 'Policiales'),
					('C', 'Cultural'),
				)
	tipo = models.CharField(max_length=1,
			choices = TIPO_CHOICE)
	slug = models.SlugField(editable=False, max_length=100)

	imagen = models.ImageField(upload_to = 'imagenes', blank = True)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.titulo)
		super(Noticia, self).save(*args, **kwargs)

	def __str__(self):
		return self.titulo

from django.conf import settings
class Comentario(TimeStampedModel):
	cuerpo = models.CharField(max_length=1000)
	autor = models.ForeignKey(settings.AUTH_USER_MODEL)
	articulo = models.ForeignKey(Noticia)
	def __str__(self):
		return 'art-'+ str(self.articulo.id) +'-'+self.autor.username

Intruzoz/apps/noticias/forms.py
from django import forms
from .models import Noticia


class Formulario(forms.ModelForm):
	class Meta:
		model = Noticia
		fields = '__all__'


class Contacto(forms.Form):
	nombre = forms.CharField(max_length=50, label='Tu nombre', required = True)
	email = forms.EmailField(label='Tu correo electronico', required = True)
	asunto = forms.CharField(max_length=50, label='Asunto', required = True)
	mensaje = forms.CharField(widget = forms.Textarea())

Intruzoz/apps/noticias/views.py
from django.shortcuts import render
from .models import Noticia, Comentario
#from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin


from .forms import Formulario, Contacto
from django.shortcuts import redirect
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required


# Create your views here.

"""
def noticias(request):
	entradas = Noticia.objects.all()
	return render (request, 'noticias/noticias.html', {'noticias' : entradas})

def mostrar_noticia(request, id_noticia):	
	articulo = Noticia.objects.get(pk = id_noticia)
	return render (request, 'noticias/noticia.html', {'noticia' : articulo})
"""

class Listar_Noticias(ListView):
	model = Noticia
	template_name = 'noticias/noticias.html'
	def get_queryset(request):
		respuesta = Noticia.objects.all().order_by('-creado')
		return respuesta

class Mostrar_Noticia(DetailView):
	model = Noticia
	template_name = 'noticias/noticia.html'
	def get_context_data(self, **kwargs):
		context = super(Mostrar_Noticia, self).get_context_data(**kwargs)
		context['comentarios'] = Comentario.objects.filter(articulo_id=self.object.id)
		return context

from django.utils import timezone
from django.http import HttpResponse
import json

@login_required
def Comentar_ajax(request):
	if request.is_ajax:
		cuerpo = request.GET.get("cuerpito",None)
		art = request.GET.get("art",None)
		posteo = Noticia.objects.get(id=art)
		autor = request.user
		dic={}
		print('si', cuerpo, art, posteo, '++')
		if cuerpo:
			print(cuerpo,art,autor,'--')
			Comentario.objects.create(cuerpo=cuerpo, autor=autor, articulo=posteo) 
			dic['cuerpo'] = cuerpo
			dic['autor'] = autor.username
			dic['creado'] = 'Ahora mismo'
			dic['bandera'] = True
		else:
			dic['bandera'] = False
		print (dic)

		return HttpResponse(json.dumps(dic), content_type="application/json")



@login_required
def Crear_Noticia(request):
	if request.method == 'POST':
		form = Formulario(request.POST)
		if form.is_valid():
			form.save()
			#post = form.save(commit=False)
			#post.author = request.user
			#post.published_date = timezone.now()
			#post.save()
			#return redirect('blog.views.post_detail', pk=post.pk)
			return redirect(reverse_lazy('noticias:noticias'))
		else:
			ctx={}
			ctx['form'] = form
			return render (request, 'noticias/crear_noticia.html', ctx)
	else:
		ctx={}
		ctx['form'] = Formulario()
	return render (request, 'noticias/crear_noticia.html', ctx)

class Editar_Noticia(LoginRequiredMixin, UpdateView):
	model = Noticia
	fields = ['titulo','resumen','cuerpo','tipo']
	template_name = 'noticias/editar_noticia.html'
	success_url= reverse_lazy('noticias:noticias')


class Eliminar_Noticia(LoginRequiredMixin, DeleteView):
	model = Noticia
	success_url = reverse_lazy('noticias:noticias')

def Contactar(request):
	if request.method == 'POST':
		form = Contacto(request.POST)
		if form.is_valid():
			Enviar_mail(form)
			return redirect(reverse_lazy('noticias:noticias'))
		else:
			ctx={}
			ctx['form'] = form
			return render (request, 'noticias/contacto.html', ctx)

	else:
		ctx={}
		ctx['form'] = Contacto()
	return render (request, 'noticias/contacto.html', ctx)

def Enviar_mail(datos):
	subject = datos.cleaned_data['asunto']
	content = datos.cleaned_data['mensaje']
	email = datos.cleaned_data['email']
	nombre = datos.cleaned_data['nombre']
	body = """Hola"""

	msg = EmailMessage(subject = subject, to = ['facustest@gmail.com'], body = body)
	msg.content_subtype = "html"
	msg.send()

Intruzoz/templates/noticias/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- Latest compiled and minified Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href={% static 'css/estilos.css' %}>
	<link rel="shortcut icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
	<link rel="icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
	<script type="text/javascript" src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
    <script type = "text/javascript" src = "https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
</head>

<body>
	<header>
		<div class="container">
			{% block header %}{% endblock %}
		</div>
	</header>

    {% block content %}{% endblock %}
    <!-- Latest compiled and minified JavaScript -->
	<script src="http://code.jquery.com/jquery-latest.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

Intruzoz/templates/noticias/contacto.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Contactarse</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href={% static 'css/estilos.css' %}>
	<link rel="shortcut icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
	<link rel="icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
</head>
<body>
	<header>
		<div class="container">
			<h1>Página Web de Prácticas</h1>
		</div>
	</header>

	<div class="container">
	<div class="row">
	<div class="col-md-6 col-md-offset-3" >
		<h1>Envianos un correo electronico.</h1>
		<form method="POST" action="">{% csrf_token %}
			{{form.as_p}}
		<button type="submit">Enviar!</button>
		</form>
	</div>
	</div>
	</div>

</body>
</html>

Intruzoz/templates/noticias/crear_noticia.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Crear Noticias</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href={% static 'css/estilos.css' %}>
	<link rel="shortcut icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
	<link rel="icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>


</head>
<body>
	<header class="container-fluid">
		<h1>Página de Práctica</h1>
	</header>
	<div class="container">
		<h1>Aqui creamos una noticia</h1>

		<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
			<h3>Titulo:</h3>
			{{form.titulo}}

			<h3>Resumen:</h3>
			{{form.resumen}}

			<h3>Descripción:</h3>
			<!-- <div style="overflow: scroll;"></div> -->
			{{form.cuerpo | safe }}

			<h3>Categoría:</h3>
			{{form.tipo}}
			<br>
			<br>
			<br>

		<button type="submit">Crear!</button>
		</form>

	</div>
</body>
	
</html>

Intruzoz/templates/noticias/editar_noticia.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Editar Noticia</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href={% static 'css/estilos.css' %}>
	<link rel="shortcut icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
	<link rel="icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
  	<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
	<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
</head>
<body>
	<header class="container-fluid">
		<h1>Página de Práctica</h1>
	</header>
	<div class="container">
	<h1>Editar Noticia!</h1>

	<form method="POST" action="">{% csrf_token %}			
		<!--{{form.titulo.label}}-->
			<h3>Titulo:</h3>
			{{form.titulo}}

			<h3>Resumen:</h3>
			{{form.resumen}}

			<h3>Descripción:</h3>
			{{form.cuerpo | safe }}

			<h3>Categoría:</h3>
			{{form.tipo}}

		<br><br>
		<button type="submit">Guardar!</button>
	</form>
	<br><br>
	</div>
</body>

</html>

Intruzoz/templates/noticias/eliminar_noticia.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Eliminar Noticia</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href={% static 'css/estilos.css' %}>
	<link rel="shortcut icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
	<link rel="icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
</head>
<body>
	<h1>Eliminar Noticia!</h1>
</body>
</html>

Intruzoz/templates/noticias/noticia.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Noticias del Info | {{noticia.titulo}}</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href={% static 'css/estilos.css' %}>
	<link rel="shortcut icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
	<link rel="icon" href={% static 'img/favicon.ico' %} type="image/x-icon">
</head>
<body>
	<header>
		<div class="container">
			<h1>Noticias del Info</h1>
		</div>
	</header>

	<div class="container">
		<h2>{{noticia.titulo}} <br><small>{{noticia.get_tipo_display}}</small></h2>

		<p class="justify">
			{{noticia.cuerpo|safe}}
		</p>
		<p>{{noticia.imagen}}</p>
		<p class="justify">
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi quae, cum dolorem inventore velit ad dolor pariatur suscipit iste laudantium, distinctio excepturi, quo laborum vitae! Officia quae, commodi sunt autem!
		</p>

		<h2 class="titulo">Comentarios:</h2>

		<div class="form-group">
 			<label for="tipcuerpo">Escribí aquí un comentario</label>
 			<textarea class="form-control" rows="3" id="comentariocuerpo" maxlength="1000"></textarea>
		</div>
		<div class="">
			<button type="button" class="btn btn-default btn-lg" id="comentar">Enviar</button>
		</div>
		<br>

		<div class="col-sm-12">
			{% for c in comentarios %}
				<div id="comentarios" class="comment">
			        <div class="date">{{ c.creado }}</div>
			        <strong>{{ c.autor }}</strong>
			        <p>{{ c.cuerpo|linebreaks }}</p>
			        <hr>
			    </div>

			{% empty %}
				<p>No hay comentarios todavía.</p>
			{% endfor %}
		</div>

	<br><br>
	</div>

	<!-- Latest compiled and minified JavaScript -->
	<script src="http://code.jquery.com/jquery-latest.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

	<script type="text/javascript">
		$(function(){
			$('#comentar').click(function(){
			var cuerpito = $('#comentariocuerpo').val();
			var art = "{{object.id}}"
			alert(cuerpito);
			alert(art);
			$.ajax({
				url : "../../Comentar_ajax",
				type : "GET",
				data : { 'cuerpito': cuerpito, 'art': art },
				
				success : function(asd){
					if (asd.bandera){
						$('#comentarios').prepend('<div class="date">'+asd.creado+'</div><strong>'+asd.autor+'</strong><p>'+asd.cuerpo+'</p><hr>')
					}
					else{
						alert('No!');
					}
				}
			});
			});
		});
	</script>


</body>
</body>
</html>

Intruzoz/templates/noticias/noticias.html
{% extends "noticias/base.html" %}


{% block title %}Noticias del Info!{% endblock %}

{% block header %}<h1>Noticias del Info!</h1>{% endblock %}

{% block content %}
	<div class="container">
		<h2>Lo último en noticias:</h2>

		{% for noticia in object_list %}
			<h3><a href={% url 'noticias:noticia' noticia.id %}{{noticia.slug}}>{{ noticia.titulo }}</a>
			<div class="btn-group"> <!-- Botones de edición -->
				<a class="btn btn-default btn-sm" href={% url 'noticias:crear_noticia' %} role="button"><span class="glyphicon glyphicon-file"></span></a>
				<a class="btn btn-default btn-sm" href={% url 'noticias:editar_noticia' noticia.id %} role="button"><span class="glyphicon glyphicon-pencil"></span></a>
				<a class="btn btn-default btn-sm" href={% url 'noticias:eliminar_noticia' noticia.id %} role="button"><span class="glyphicon glyphicon-trash"></span></a></div></h3>
			<h4>{{ noticia.resumen }}</h4>
			<h5>En {{ noticia.get_tipo_display }}</h4>
			
			<hr>
		{%endfor%}

	</div>
{% endblock %}